In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
import os
import gdown
from zipfile import ZipFile
from sklearn.preprocessing import StandardScaler

import tensorflow_datasets as tfds

In [ ]:
import zipfile
###############將要訓練的zip_file解壓縮###########
with zipfile.ZipFile("./one_line_data.zip", "r") as zip_ref:
    zip_ref.extractall("one_line_data")####要自己創一個放壓縮後data的資料夾########

In [ ]:
############CASE2########################
BALL_X=[-800,-800,-3200,-3200,0,0,2400,2400,800,800,5600,5600,4000,4000,2400,2400,5600,5600]
BALL_Y=[4800,4000,2400,3200,2400,3200,4800,4000,5600,6400,800,1600,2400,3200,-3200,-2400,-2400,-1600]
BUMP_X=[-1315.88,-1168.96,-581.25,-583.86,6.46,-140.47,580.37,712.96,1109.59,1241.62,1541.2,1541.2,1541.2,1541.2,1466.99,1466.99,1541.2,1541.2]
BUMP_Y=[1268.35,1268.35,963.79,1119.07,1268.35,1268.35,1133.21,1265.45,1133.21,1265.45,840.71,980.79,420.3,280.13,-140.29,-280.45,-840.95,-700.87]
print("BALL_X=",BALL_X)
print("BALL_Y=",BALL_Y)
print("BUMP_X=",BUMP_X)
print("BUMP_Y=",BUMP_Y)


start_nodeX=np.zeros((int(len(BALL_X)/2)))
end_nodeX=np.zeros((int(len(BALL_X)/2)))
start_nodeY=np.zeros((int(len(BALL_X)/2)))
end_nodeY=np.zeros((int(len(BALL_X)/2)))
count=0
#for i in range(0,len(BALL_X),2):
#  start_nodeX[count]=(BALL_X[i]+BALL_X[i+1])/2
#  end_nodeX[count]=(BUMP_X[i]+BUMP_X[i+1])/2
#  start_nodeY[count]=(BALL_Y[i]+BALL_Y[i+1])/2
#  end_nodeY[count]=(BUMP_Y[i]+BUMP_Y[i+1])/2
#  count=count+1
for i in range(0,len(BALL_X),2):
  start_nodeX[count]=BALL_X[i]
  end_nodeX[count]=BUMP_X[i]
  start_nodeY[count]=BALL_Y[i]
  end_nodeY[count]=BUMP_Y[i]
  count=count+1
print("start_nodeX=",start_nodeX)
print("start_nodeY=",start_nodeY)
print("end_nodeX=",end_nodeX)
print("end_nodeY=",end_nodeY)
start_row_data=np.zeros((int(len(BALL_X)/2)))
goal_row_data=np.zeros((int(len(BALL_X)/2)))
start_col_data=np.zeros((int(len(BALL_X)/2)))
goal_col_data=np.zeros((int(len(BALL_X)/2)))
for i in range(len(start_nodeX)):
  start_row_data[i]=start_nodeX[i]+7000
  goal_row_data[i]=end_nodeX[i]+7000
  start_col_data[i]=start_nodeY[i]+7000
  goal_col_data[i]=end_nodeY[i]+7000
print("start_row_data=",start_row_data)
print("start_col_data=",start_col_data)
print("goal_row_data=",goal_row_data)
print("goal_col_data=",goal_col_data)
for i in range(len(start_nodeX)):
  start_row_data[i]=int(start_row_data[i]/219)
  start_col_data[i]=int(start_col_data[i]/219)
  goal_row_data[i]=int(goal_row_data[i]/219)
  goal_col_data[i]=int(goal_col_data[i]/219)
print("start_row_data=",start_row_data)
print("start_col_data=",start_col_data)
print("goal_row_data=",goal_row_data)
print("goal_col_data=",goal_col_data)


############Bump range#############
up_left_x=-1711.5
up_left_y=1393.52
up_right_x=1711.5
up_right_y=1393.52
down_left_x=-1711.5
down_left_y=-1393.52
down_right_x=1711.5
down_right_y=-1393.52
print("Before resize:")
print("up_left_x=",up_left_x)
print("up_left_y=",up_left_y)
print("up_right_x=",up_right_x)
print("up_right_y=",up_right_y)
print("down_left_x=",down_left_x)
print("down_left_y=",down_left_y)
print("down_right_x=",down_right_x)
print("down_right_y=",down_right_y)
up_left_x=int((up_left_x+7000)/219)
up_left_y=int((up_left_y+7000)/219)
up_right_x=int((up_right_x+7000)/219)
up_right_y=int((up_right_y+7000)/219)
down_left_x=int((down_left_x+7000)/219)
down_left_y=int((down_left_y+7000)/219)
down_right_x=int((down_right_x+7000)/219)
down_right_y=int((down_right_y+7000)/219)
print("After resize:")
print("up_left_x=",up_left_x)
print("up_left_y=",up_left_y)
print("up_right_x=",up_right_x)
print("up_right_y=",up_right_y)
print("down_left_x=",down_left_x)
print("down_left_y=",down_left_y)
print("down_right_x=",down_right_x)
print("down_right_y=",down_right_y)
min_row=min(up_left_x,up_right_x,down_left_x,down_right_x)
min_col=min(up_left_y,up_right_y,down_left_y,down_right_y)
max_row=max(up_left_x,up_right_x,down_left_x,down_right_x)
max_col=max(up_left_y,up_right_y,down_left_y,down_right_y)
print("min_row=",min_row)
print("min_col=",min_col)
print("Max_row=",max_row)
print("Max_col=",max_col)

BALL_X= [-800, -800, -3200, -3200, 0, 0, 2400, 2400, 800, 800, 5600, 5600, 4000, 4000, 2400, 2400, 5600, 5600]
BALL_Y= [4800, 4000, 2400, 3200, 2400, 3200, 4800, 4000, 5600, 6400, 800, 1600, 2400, 3200, -3200, -2400, -2400, -1600]
BUMP_X= [-1315.88, -1168.96, -581.25, -583.86, 6.46, -140.47, 580.37, 712.96, 1109.59, 1241.62, 1541.2, 1541.2, 1541.2, 1541.2, 1466.99, 1466.99, 1541.2, 1541.2]
BUMP_Y= [1268.35, 1268.35, 963.79, 1119.07, 1268.35, 1268.35, 1133.21, 1265.45, 1133.21, 1265.45, 840.71, 980.79, 420.3, 280.13, -140.29, -280.45, -840.95, -700.87]
start_nodeX= [ -800. -3200.     0.  2400.   800.  5600.  4000.  2400.  5600.]
start_nodeY= [ 4800.  2400.  2400.  4800.  5600.   800.  2400. -3200. -2400.]
end_nodeX= [-1315.88  -581.25     6.46   580.37  1109.59  1541.2   1541.2   1466.99
  1541.2 ]
end_nodeY= [1268.35  963.79 1268.35 1133.21 1133.21  840.71  420.3  -140.29 -840.95]
start_row_data= [ 6200.  3800.  7000.  9400.  7800. 12600. 11000.  9400. 12600.]
start_col_data= [11800.  

In [ ]:
############CASE1########################
BALL_X=[314.96,-548.64,-2275.84,-3139.44,-5950,-5950,-5950,-5950,-5543.55,-5950,-5543.55,-5950,-4681.73,-4754.45,-1412.24,-548.64,1178.56,1610.36]
BALL_Y=[5750,5750,5750,5750,3124.2,2260.6,533.4,-330.2,-1625.6,-2057.4,-3352.8,-3860.8,-5153.1,-5750,-5750,-5750,-5750,-5343.55]
BUMP_X=[-1022.03,-1022.03,-1168.96,-1315.88,-1462.81,-1462.81,-1540.56,-1540.56,-1401.09,-1401.09,-1120.99,-1120.99,-980.92,-840.85,-442.24,-442.34,-302.17,-302.17]
BUMP_Y=[1121.42,1268.35,1268.35,1268.35,754.17,544.56,-68.42,-218.28,-657.31,-797.39,-988.21,-1128.28,-1268.35,-1268.35,-848.14,-988.21,-1268.35,-1128.28]
print("BALL_X=",BALL_X)
print("BALL_Y=",BALL_Y)
print("BUMP_X=",BUMP_X)
print("BUMP_Y=",BUMP_Y)


start_nodeX=np.zeros((int(len(BALL_X)/2)))
end_nodeX=np.zeros((int(len(BALL_X)/2)))
start_nodeY=np.zeros((int(len(BALL_X)/2)))
end_nodeY=np.zeros((int(len(BALL_X)/2)))
count=0
#for i in range(0,len(BALL_X),2):
#  start_nodeX[count]=(BALL_X[i]+BALL_X[i+1])/2
#  end_nodeX[count]=(BUMP_X[i]+BUMP_X[i+1])/2
#  start_nodeY[count]=(BALL_Y[i]+BALL_Y[i+1])/2
#  end_nodeY[count]=(BUMP_Y[i]+BUMP_Y[i+1])/2
#  count=count+1
for i in range(0,len(BALL_X),2):
  start_nodeX[count]=BALL_X[i]
  end_nodeX[count]=BUMP_X[i]
  start_nodeY[count]=BALL_Y[i]
  end_nodeY[count]=BUMP_Y[i]
  count=count+1
print("start_nodeX=",start_nodeX)
print("start_nodeY=",start_nodeY)
print("end_nodeX=",end_nodeX)
print("end_nodeY=",end_nodeY)
start_row_data=np.zeros((int(len(BALL_X)/2)))
goal_row_data=np.zeros((int(len(BALL_X)/2)))
start_col_data=np.zeros((int(len(BALL_X)/2)))
goal_col_data=np.zeros((int(len(BALL_X)/2)))
for i in range(len(start_nodeX)):
  start_row_data[i]=start_nodeX[i]+6100
  goal_row_data[i]=end_nodeX[i]+6100
  start_col_data[i]=start_nodeY[i]+6300
  goal_col_data[i]=end_nodeY[i]+6300
print("start_row_data=",start_row_data)
print("start_col_data=",start_col_data)
print("goal_row_data=",goal_row_data)
print("goal_col_data=",goal_col_data)
for i in range(len(start_nodeX)):
  start_row_data[i]=int(start_row_data[i]/198)
  start_col_data[i]=int(start_col_data[i]/198)
  goal_row_data[i]=int(goal_row_data[i]/198)
  goal_col_data[i]=int(goal_col_data[i]/198)
print("start_row_data=",start_row_data)
print("start_col_data=",start_col_data)
print("goal_row_data=",goal_row_data)
print("goal_col_data=",goal_col_data)




BALL_X= [314.96, -548.64, -2275.84, -3139.44, -5950, -5950, -5950, -5950, -5543.55, -5950, -5543.55, -5950, -4681.73, -4754.45, -1412.24, -548.64, 1178.56, 1610.36]
BALL_Y= [5750, 5750, 5750, 5750, 3124.2, 2260.6, 533.4, -330.2, -1625.6, -2057.4, -3352.8, -3860.8, -5153.1, -5750, -5750, -5750, -5750, -5343.55]
BUMP_X= [-1022.03, -1022.03, -1168.96, -1315.88, -1462.81, -1462.81, -1540.56, -1540.56, -1401.09, -1401.09, -1120.99, -1120.99, -980.92, -840.85, -442.24, -442.34, -302.17, -302.17]
BUMP_Y= [1121.42, 1268.35, 1268.35, 1268.35, 754.17, 544.56, -68.42, -218.28, -657.31, -797.39, -988.21, -1128.28, -1268.35, -1268.35, -848.14, -988.21, -1268.35, -1128.28]
start_nodeX= [  314.96 -2275.84 -5950.   -5950.   -5543.55 -5543.55 -4681.73 -1412.24
  1178.56]
start_nodeY= [ 5750.   5750.   3124.2   533.4 -1625.6 -3352.8 -5153.1 -5750.  -5750. ]
end_nodeX= [-1022.03 -1168.96 -1462.81 -1540.56 -1401.09 -1120.99  -980.92  -442.24
  -302.17]
end_nodeY= [ 1121.42  1268.35   754.17   -68.42  -657

In [ ]:
import zipfile
import numpy as np
import cv2
#############將線段座標存入陣列([](要train的data數)[](rol)[](col)[](一筆data所分的層數))####################
import sys
import random
from PIL import Image
training_data_num=1314
x=64
y=64
num_channels=1
batch_size=64
count_batch=0
mod=training_data_num%batch_size
times=int(training_data_num/batch_size)

if mod!=0:
  times=times+1
count_times=0
total_data=np.zeros((times,batch_size,x,y,num_channels))
for num in range(training_data_num):
  idx_x=0
  idx_y=0
  img = Image.open("./one_line_data/"+str(num)+".jpg")
  resize_img = img.resize((64, 64))
  data = np.asarray(resize_img)
  for i in range(x):
    for j in range(y):
      total_data[count_times][count_batch][idx_x][idx_y][0]=float(data[i][j])
      idx_y=idx_y+1
      if idx_y==64:
        idx_y=0
        idx_x=idx_x+1
  count_batch=count_batch+1
  if (count_batch==batch_size):
    count_batch=0
    count_times=count_times+1

numpy_data=np.zeros((times,batch_size,x,y,num_channels), dtype=float)
for i in range(times):
  numpy_data[i]=total_data[i]
feature = tf.constant(numpy_data,dtype=np.float32,shape=(times,batch_size,x,y,num_channels))
dataset_6464 = tf.data.Dataset.from_tensor_slices(feature)
dataset_6464 = dataset_6464.map(lambda x: 2*((x-0)/255)-1)####原本/255

In [ ]:
##############Class Model##############
#############功能: 將訓練中還不成熟的矩陣內的pixel快速分類(讓他能變成一條線###########
####起始位置###############
start_row=int(start_row_data[4])
start_col=int(start_col_data[4])

####目標的位置
goal_row=int(goal_row_data[4])
goal_col=int(goal_col_data[4])

if start_row>goal_row and start_col<goal_col:
  temp=start_row
  start_row=goal_row
  goal_row=temp
  temp1=start_col
  start_col=goal_col
  goal_col=temp1
if start_row>goal_row and start_col>goal_col:
  temp=start_row
  start_row=goal_row
  goal_row=temp
  temp1=start_col
  start_col=goal_col
  goal_col=temp1
if start_row>goal_row and start_col==goal_col:
  temp=start_row
  start_row=goal_row
  goal_row=temp
  temp1=start_col
  start_col=goal_col
  goal_col=temp1
if start_row==goal_row and start_col>goal_col:
  temp=start_row
  start_row=goal_row
  goal_row=temp
  temp1=start_col
  start_col=goal_col
  goal_col=temp1
def turn_result(matrix):
  for i in range(64):
    for j in range(64):
      if matrix[i][j]==0 or matrix[i][j]==255 or matrix[i][j]==10 or matrix[i][j]==50 or matrix[i][j]==30 or matrix[i][j]==60 or matrix[i][j]==70 or matrix[i][j]==80: 
        continue
      else:
        matrix[i][j]=0
  print("turn_result=\n",matrix)
  return matrix

def draw(matrix,row,col,step,dir):
  old_row=row
  old_col=col
  is_break=0
  if dir==0:#####右
    for i in range(step):
      #print("eeeee")
      if col>=64 or row>=64 or col<0 or row<0:
        is_break=1
        break
      matrix[row][col]=10
      col=col+1
    if is_break==0:
      matrix[row][col]=255#######轉折點是255
    else:
      col=col-1
      matrix[row][col-1]=255 
  if dir==1:#####右下
    for i in range(step):
      #print("fffff")
      if col>=64 or row>=64 or col<0 or row<0:
        is_break=1
        break
      matrix[row][col]=80
      col=col+1
      row=row+1
    if is_break==0:
      matrix[row][col]=255#######轉折點是255
    else:
      row=row-1
      col=col-1
      matrix[row-1][col-1]=255  
  if dir==2:#####下
    for i in range(step):
      #print("ggggg")
      if col>=64 or row>=64 or col<0 or row<0:
        is_break=1
        break
      matrix[row][col]=70
      row=row+1
    if is_break==0:
      matrix[row][col]=255#######轉折點是255
    else:
      row=row-1
      matrix[row-1][col]=255     
  if dir==4:#####左
    for i in range(step):
      #print("hhhhh")
      if col>=64 or row>=64 or col<0 or row<0:
        is_break=1
        break
      matrix[row][col]=50
      col=col-1
    if is_break==0:
      matrix[row][col]=255#######轉折點是255
    else:
      col=col+1
      matrix[row][col+1]=255 
  if dir==3:#####左下
    for i in range(step):
      #print("AAAAAAAAAAAAAAAAAAAA")
      if col>=64 or row>=64 or col<0 or row<0:
        is_break=1
        break
      matrix[row][col]=60
      col=col-1
      row=row+1
    if is_break==0:
      #print("row=",row)
      #print("col=",col)
      matrix[row][col]=255#######轉折點是255
    else:
      row=row-1
      col=col+1
      matrix[row-1][col+1]=255
  matrix[old_row][old_col]=255
  return matrix,row,col 
  #print("after_draw:\n",matrix)  
def go_test(matrix,now_row,now_col,goal_row,goal_col,step,before_dir):
  if now_row<goal_row and now_col>goal_col:####################起點在右上 終點在左下#####
    if before_dir==-1:###########get started########
      rand_dir=random.randrange(0, 3)
      if rand_dir==0:
        dir=4
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==1:
        dir=3
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==2:
        dir=2
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
    if before_dir==4:###########get started########
      rand_dir=random.randrange(0, 2)
      if rand_dir==0:
        dir=4
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==1:
        dir=3
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
    if before_dir==3:###########get started########
      rand_dir=random.randrange(0, 3)
      if rand_dir==0:
        dir=4
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==1:
        dir=3
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==2:
        dir=2
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
    if before_dir==2:###########get started########
      rand_dir=random.randrange(0, 2)
      if rand_dir==0:
        dir=3
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==1:
        dir=2
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
  if now_row<goal_row and now_col<goal_col:####################起點在左上 終點在右下#####
    if before_dir==-1:###########get started########
      rand_dir=random.randrange(0, 3)
      if rand_dir==0:
        dir=0
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==1:
        dir=1
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==2:
        dir=2
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
    if before_dir==0:###########get started########
      rand_dir=random.randrange(0, 2)
      if rand_dir==0:
        dir=0
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==1:
        dir=1
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
    if before_dir==1:###########get started########
      rand_dir=random.randrange(0, 3)
      if rand_dir==0:
        dir=0
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==1:
        dir=1
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==2:
        dir=2
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
    if before_dir==2:###########get started########
      rand_dir=random.randrange(1, 3)
      if rand_dir==1:
        dir=1
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
      if rand_dir==2:
        dir=2
        before_dir=dir
        matrix,now_row,now_col=draw(matrix,now_row,now_col,step,dir)
  return matrix,now_row,now_col,before_dir
def draw_one_line(matrix,start_row,start_col,goal_row,goal_col):
  if start_row==goal_row:
    diff_col=abs(goal_col-start_col)
    for i in range(1,diff_col):
      matrix[start_row][start_col+i]=10
  if start_col==goal_col:
    diff_row=abs(goal_row-start_row)
    for i in range(1,diff_row):
      if start_row+i<64:
        matrix[start_row+i][start_col]=70
  return matrix      

def custom_model(gen_result):
  #print(matrix.shape)
  matrix = np.zeros((64,64), dtype = float)
  for i in range(64):
    for j in range(64):
      matrix[i][j]=gen_result[0][i][j][0]
  
  
  ####目前所在的位置
  now_row=int(start_row)
  now_col=int(start_col)
  if (abs(start_row-goal_row)==1 and abs(start_col-goal_col)==1) or (abs(start_row-goal_row)==1 and abs(start_col-goal_col)==0) or (abs(start_row-goal_row)==0 and abs(start_col-goal_col)==1):
    matrix[start_row][start_col]=255
    matrix[goal_row][goal_col]=255
    return matrix
  node_num=random.randrange(2,3)#####決定起點到終點之間會有幾個轉折點
  print("\nnum(turn_node)=",node_num)
  count_node=0
  matrix[now_row][now_col]=255
  matrix[goal_row][goal_col]=255
  before_dir=-1
  end=0
  while(end==0):
    step=random.randrange(2, 3)
    matrix,now_row,now_col,before_dir=go_test(matrix,now_row,now_col,goal_row,goal_col,step,before_dir)
    count_node=count_node+1
    if count_node>=node_num:
      end=1
    if start_row==goal_row or start_col==goal_col:
      matrix=draw_one_line(matrix,start_row,start_col,goal_row,goal_col)
      end=1
  #print("matrix[now_row][now_col]=",matrix[now_row][now_col])
  #print("matrix[goal_row][goal_col]=",matrix[goal_row][goal_col])
  return matrix

In [ ]:

custom_predict = keras.Sequential(
    [
        keras.Input(shape=(64, 64, num_channels)),
        layers.Conv2D(64, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.Conv2D(128, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.BatchNormalization(),
        layers.Conv2D(128, kernel_size=4, strides=2, padding="same"),
        layers.LeakyReLU(alpha=0.2),
        layers.BatchNormalization(),
        layers.Flatten(),
        #layers.Dropout(0.2),
        layers.Dense(1, activation="sigmoid"),###原本是sigmoid
    ],
    name="custom_predict",
)
custom_predict.summary()

Model: "custom_predict"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 64)        1088      
                                                                 
 leaky_re_lu (LeakyReLU)     (None, 32, 32, 64)        0         
                                                                 
 conv2d_1 (Conv2D)           (None, 16, 16, 128)       131200    
                                                                 
 leaky_re_lu_1 (LeakyReLU)   (None, 16, 16, 128)       0         
                                                                 
 batch_normalization (BatchN  (None, 16, 16, 128)      512       
 ormalization)                                                   
                                                                 
 conv2d_2 (Conv2D)           (None, 8, 8, 128)         262272    
                                                    

In [ ]:
###################CUSTOM PREDICTION: Discriminator用來預測是真實圖還是假的圖#####################
def SearchLine(picture, finished_picture):
    global first_x, first_y
    for i in range(np.size(picture,0)):
        for j in range(np.size(picture,1)):
            if int(picture[i][j]) == 255 and finished_picture[i][j] == 0: #have diff pair
                first_x = i
                first_y = j
                return i, j

    return -1, -1

def checkpoint(x, y, picture, finished_picture, x_Max, y_Max, pre, state,err):
    #global err
    global last_x, last_y
    global long

    if err==False:
        return
    if x < 0 or x >= x_Max or y < 0 or y >= y_Max:
        return
    picture[x][y]=int(picture[x][y])
    #print(x,y,finished_picture)

    if picture[x][y]==0 or finished_picture[x][y]==1:
        return
    long += 1
    finished_picture[x][y]=1
    
    last_x = x
    last_y = y
    if state!=pre and pre!=-1:
        if abs(state-pre)!=1 and abs(state-pre)!=7:
            #print('in')
            err=False
            return
    ty = [-1, 0, 1,1,1,0,-1,-1]
    tx = [-1,-1,-1,0,1,1, 1, 0]
    for i in range(8):
        nextx = x+tx[i]
        nexty = y+ty[i]
        
        checkpoint(nextx,nexty,picture,finished_picture,x_Max,y_Max,state,i,err)
    return
     

def rule1(x_Max, y_Max, combined_images, finished_picture,err): # must 45-degree angle
    #x = np.zeros((64,64,1))
    picture = np.zeros((64,64))
    for i in range(64):
      for j in range(64):
        picture[i][j]=combined_images[i][j][0]  
    x, y = SearchLine(picture, finished_picture)

    checkpoint(x, y, picture, finished_picture, x_Max, y_Max, -1, -1,err)
    



def rule2(x_Max, y_Max, combined_images, finished_picture, inputlist, ablist, tolerance): 
      
    diff_A = 0
    picture = np.zeros((64,64))
    for i in range(64):
      for j in range(64):
        picture[i][j]=combined_images[i][j][0]  
    
    ax = abs( ablist[0] - inputlist[0] )
    ay = abs( ablist[1] - inputlist[1] )
    while ax > 0 and ay > 0:
        diff_A+=1
        ax-=1
        ay-=1
    
    diff_A+=ax+ay
    
    
    diff_B=0
    bx = abs( ablist[2] - inputlist[2] )
    by = abs( ablist[3] - inputlist[3] )
    while bx > 0 and by > 0:
        diff_B+=1
        bx-=1
        by-=1
    
    diff_B+=bx+by
    
    if diff_A > tolerance or diff_B > tolerance :        
        return False
    
    
    
    

    
    #print('rule2:True')
    
    return True 

def rule3(pic_len, ablist): 
    # print( 'A_x : ', ablist[0]+1, 'A_y : ', ablist[1]+1, ', B_x : ', ablist[2]+1, 'B_y : ', ablist[3]+1 )
    
    # print( 'InputA_x : ', inputlist[0]+1, 'InputB_y : ', inputlist[1]+1, ', InputB_x : ', inputlist[2]+1, 'InputB_y : ', inputlist[3]+1 )
    n = 2
    diff = 0
    
    
    ax = abs( ablist[0] - ablist[2] )
    ay = abs( ablist[1] - ablist[3] )
    while ax > 0 and ay > 0:
        diff+=1
        ax-=1
        ay-=1
    
    diff+=ax+ay
    
    #print('the shortest path : ', diff)

    
    if pic_len > diff * n:
        #print('False. the path is too long : ', pic_len )
        return False
    else:
        #print('True')
        return True
def checkoverlap(x, y, picture, finished_picture, x_Max, y_Max):
    err2=False

    if err2==False:
        return
    if x < 0 or x >= x_Max or y < 0 or y >= y_Max:
        return
    
    if picture[x][y]==0 or finished_picture[x][y]==1:
        return

    finished_picture[x][y]=1
    
    ty = [-1, 0, 1,1,1,0,-1,-1]
    tx = [-1,-1,-1,0,1,1, 1, 0]
    
    # print('x = ', x, 'y = ', y )
    count = 0
    for i in range(8):

        nextx = x+tx[i]
        nexty = y+ty[i]
        
        
        # print('nextx = ', nextx, 'nexty = ', nexty )
        
        if nextx < 0 or nextx >= x_Max or nexty < 0 or nexty >= y_Max:
            continue
        elif not picture[nextx][nexty]==0 :
            # print('count++')
            count+=1
            
        checkoverlap(nextx, nexty, picture, finished_picture, x_Max, y_Max)

    # print( 'count:', count )
    if count > 2 : 
        err2 = False    
    
    
    return
def rule4(x_Max, y_Max, picture, finished_picture): # must 45-degree angle

    x, y = SearchLine(picture, finished_picture)

    checkoverlap(x, y, picture, finished_picture, x_Max, y_Max)
def custom_predictor(combined_images):
  matrix_row=64
  matrix_col=64
  predict_result= np.zeros((128,1))
  combined_images=combined_images.numpy()
  for i in range(len(combined_images)):
    r1, r2, r3,r4 = True, True, True, True
    x_Max =  matrix_row
    y_Max =  matrix_col
    # ---------------------------rule1--------------------------------------
    finished_picture = []
    finished_picture2 = []
    for x in range(x_Max):
        finished_picture.append([0]*(y_Max))
        finished_picture2.append([0]*(y_Max))
    first_x = 0
    first_y = 0
    last_x = 0
    last_y = 0
    long = -1
    err = True
    err2 = True
    rule1(x_Max, y_Max, combined_images[i], finished_picture,err)
    if err==True:
        #print('Rule1:True')
        r1 = True
    else:
        #print('Rule1:False')
        r1 = False
    # ---------------------------rule2--------------------------------------
    #print('--------------------------------------------')
    #print('rule2')

    ablist = [] # store ab loacation
    inputlist = [] # store detect diff ab location
    
    inputlist.append(first_x)
    inputlist.append(first_y)
    inputlist.append(last_x)
    inputlist.append(last_y)
    

    #axy = input("Input A (x, y) : ")
    #A_x, A_y = axy.split(' ')
    ablist.append(start_row)
    ablist.append(start_col)

    #bxy = input('Input B (x, y) : ')
    #B_x, B_y = bxy.split(' ')    
    ablist.append(goal_row)
    ablist.append(goal_col)

    tolerance = matrix_row
    r2 = rule2(x_Max, y_Max, combined_images[i], finished_picture, inputlist, ablist, tolerance)

    r3 = rule3(long, ablist)
    
    
    for i in range(len(combined_images)):
      rule4(x_Max, y_Max, combined_images[i], finished_picture2)

      if err2==True:
        #print('Rule4:True')
        r4 = True
      else:
        #print('Rule4:False')
        r4 = False
    # -----------------------------------------------------------------
    print('--------------------------------------------')   
    if r1 and r2 and r3 and r4:
      return True
    else:
      return False
  return predict_result

In [ ]:
latent_dim = 128
IMAGE_SHAPE = (64, 64, 1)
generator = keras.Sequential(
    [
        keras.Input(shape=(latent_dim,)),
        layers.Dense(32),
        layers.LeakyReLU(alpha=0.2),#原本是LeakyReLU
        layers.BatchNormalization(momentum=0.8),
        layers.Dense(64),
        layers.LeakyReLU(alpha=0.2),#原本是LeakyReLU
        layers.BatchNormalization(momentum=0.8),
        layers.Dense(np.prod(IMAGE_SHAPE),activation='tanh'),
        layers.Reshape(IMAGE_SHAPE)
    ],
    name="generator",
)
generator.summary()

Model: "generator"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 32)                4128      
                                                                 
 leaky_re_lu_3 (LeakyReLU)   (None, 32)                0         
                                                                 
 batch_normalization_2 (Batc  (None, 32)               128       
 hNormalization)                                                 
                                                                 
 dense_2 (Dense)             (None, 64)                2112      
                                                                 
 leaky_re_lu_4 (LeakyReLU)   (None, 64)                0         
                                                                 
 batch_normalization_3 (Batc  (None, 64)               256       
 hNormalization)                                         

In [ ]:
def custom_predict_loss(real_output, fake_output):
    return tf.keras.metrics.binary_crossentropy(real_output, fake_output)

In [ ]:
def generator_loss(real_output, fake_output):
    return tf.keras.metrics.binary_crossentropy(real_output, fake_output)

In [ ]:
###################LOSS1###########################產生的起點終點是否符合要求################

import sys
import numpy as np
import math


def count(result_np,i,j):
    count=0
    if (i+1)<=63 and result_np[i+1][j]!=float(0):
        count=count+1
    if (j+1)<=63 and result_np[i][j+1]!=float(0):
        count=count+1
    if (i-1)>=0 and result_np[i-1][j]!=float(0):
        count=count+1
    if (j-1)>=0 and result_np[i][j-1]!=float(0):
        count=count+1
    if (i+1)<=63 and (j+1)<=63 and result_np[i+1][j+1]!=float(0):
        count=count+1
    if (i+1)<=63 and (j-1)>=0 and result_np[i+1][j-1]!=float(0):
        count=count+1
    if (i-1)>=0 and (j-1)>=0 and result_np[i-1][j-1]!=float(0):
        count=count+1
    if (i-1)>=0 and (j+1)<=63 and result_np[i-1][j+1]!=float(0):
        count=count+1
    return count
  
  


def find_start_end(result_np):
  start_end=np.zeros((2, 2),dtype=np.int)#######64*64=4096且存x/y資料##########
  index=0
  count_node=0
  start_end[0][0]=start_row
  start_end[0][1]=start_col
  start_end[1][0]=goal_row
  start_end[1][1]=goal_col
  return start_end
  
def Distance(p1):
  #print("p2[0]=",p2[0])
  #print("p2[1]=",p2[1])
  dx = abs(p1[0] - p1[2])
  dy = abs(p1[1] - p1[3])
  num=dx*dx+dy*dy
  d = num**0.5
  return d

def angle(v1, v2):
  dx1 = v1[2] - v1[0]
  dy1 = v1[3] - v1[1]
  dx2 = v2[2] - v2[0]
  dy2 = v2[3] - v2[1]
  angle1 = math.atan2(dy1, dx1)
  angle1 = float(angle1 * 180/math.pi)
  angle2 = math.atan2(dy2, dx2)
  angle2 = float(angle2 * 180/math.pi)
    
  if angle1*angle2 >= 0:
    included_angle = abs(angle1-angle2)
  else:
    included_angle = abs(angle1) + abs(angle2)
    if included_angle > 180:
      included_angle = 360 - included_angle
  return included_angle

#############取與下面角度差距最小的值##############
def min_angle(angle):
  zero=abs(angle-0)
  one=abs(angle-45)
  two=abs(angle-90)
  three=abs(angle-135)
  four=abs(angle-180)
  return min(zero,one,two,three,four)

def LOSS1(matrix):
  print("###################LOSS1###########################產生的起點終點是否符合要求################")
  start_end=find_start_end(matrix)
  print("start_end=",start_end)
  print("last_node=",start_end[1])
  

  #########只需計算最後一個轉折點與終點的角度###############
  B_vector=np.zeros(4)########存B的水平向量########
  B_vector[0]=goal_row
  B_vector[1]=goal_col
  B_vector[2]=goal_row
  B_vector[3]=goal_col
  vector_first_B=np.zeros(4)########存B和另一點的向量########
  vector_first_B[0]=goal_row
  vector_first_B[1]=goal_col
  vector_first_B[2]=start_end[1][0]
  vector_first_B[3]=start_end[1][1]
  punish_last_angle=min_angle(angle(B_vector, vector_first_B))
  print("last_angle=",punish_last_angle)
  return punish_last_angle

In [ ]:
##############LOSS2##############################線段是否超過bump############
import sys
import numpy as np
import math
import pandas as pd


def check_bump(save_255point,min_row,min_col,max_row,max_col):
  flag=0 #########記錄走線是否曾經離開過bump邊界############
  bump_punish_time=0
  bump_total_punish=0
  total_x=max_row-min_row
  total_y=max_col-min_col
  #print("\n################################Check Bump#############################\n")
  for i in range(len(save_255point[0])):
    if (save_255point[1][i]<=min_row or save_255point[1][i]>=max_row) or (save_255point[0][i]<=min_col or save_255point[0][i]>=max_col):
      if flag==0:
        flag=1###############曾經離開過bump############
        #print("###############曾經離開過bump############")
        #print("node:(",save_255point[1][i],",",save_255point[0][i],")")
    else:
      if flag==1:###############曾經離開過bump但又跑回去bump內了############
        print("punish node: (",save_255point[1][i],",",save_255point[0][i],")")
        bump_punish_time=bump_punish_time+1
        #bump_total_punish=bump_total_punish+((save_255point[1][i]-min_row)/total_x+(save_255point[0][i]-min_col)/total_y)
      


    

  print("\nbump_punish_time=",bump_punish_time)
  #print("bump_total_punish=",bump_total_punish)
  return bump_punish_time




def gogogo(matrix,start_end,count_255):
    index_x=int(start_end[0][0])####初始位置
    index_y=int(start_end[0][1])
    end_x=start_end[1][0]
    end_y=start_end[1][1]
    
    
    arr_255point=np.zeros((2,count_255))
    arr_255point[0][0]=start_end[0][0]
    arr_255point[1][0]=start_end[0][1]
    before=-1
    run=0
    flag=0
    while(run<(count_255-1)):
        flag=0
        run=run+1
        if matrix[index_x][index_y+1]!=float(0) and flag==0:
          for i in range(64):
            if index_y+1<64:
              index_y=index_y+1
              #print(index_x,"aaaa",index_y)
              if matrix[index_x][index_y]==float(255) and flag==0:
                break
          arr_255point[0][run]=index_x
          arr_255point[1][run]=index_y
          flag=1
          #print("arr_255point=aaaa",arr_255point)
        if matrix[index_x+1][index_y+1]!=float(0) and flag==0:
          for i in range(64):
            if index_y+1<64 and index_x+1<64:
              index_y=index_y+1
              index_x=index_x+1
            #print(index_x,"bbbb",index_y)
              if matrix[index_x][index_y]==float(255):
                break
          #print("index_x=",index_x)
          arr_255point[0][run]=index_x
          arr_255point[1][run]=index_y
          flag=1
          #print("arr_255point=bbbb",arr_255point)
        if matrix[index_x+1][index_y]!=float(0) and flag==0:
          for i in range(64):
            if index_x+1<64:
              index_x=index_x+1
              #print(index_x,"cccc",index_y)
              if matrix[index_x][index_y]==float(255):
                break
          arr_255point[0][run]=index_x
          arr_255point[1][run]=index_y
          flag=1
          #print("arr_255point=cccc",arr_255point)
        if matrix[index_x][index_y-1]!=float(0) and flag==0:
          for i in range(64):
            if index_y-1>=0:
              index_y=index_y-1
              #print(index_x,"dddd",index_y)
              if matrix[index_x][index_y]==float(255):
                break
          arr_255point[0][run]=index_x
          arr_255point[1][run]=index_y
          flag=1
          #print("arr_255point=dddd",arr_255point)
        if index_x+1<64 and index_y-1>=0:
          if matrix[index_x+1][index_y-1]!=float(0) and flag==0:
            for i in range(64):
              if index_x+1<64 and index_y-1>=0:
                index_x=index_x+1
                index_y=index_y-1
                #print(index_x,"eeee",index_y)
                if matrix[index_x][index_y]==float(255):
                  break
            arr_255point[0][run]=index_x
            arr_255point[1][run]=index_y
            flag=1
          #print("arr_255point=eeee",arr_255point)
    #print("走線順序:")
    #for i in range(len(arr_255point[0])):
      #print("(",arr_255point[0][i],",",arr_255point[1][i],")")
    #print("\nbefore turn arr_255point=\n",arr_255point)
    return arr_255point

           
        

def find_255point(result_np):
    count_255=0
    for i in range(len(result_np)):
      for j in range(len(result_np)):
        if result_np[i][j]==float(255):
          count_255=count_255+1
    return count_255-1
  
  

def LOSS2(matrix):
  print("##############LOSS2##############################check bump############")
  bump_total_punish=0
  count_255=find_255point(matrix)
  #print("count_255=",count_255)
  start_end=find_start_end(matrix)
  #print(start_end)
  #############這裡假設bump_temp的陣列座標分別如下#################
  #print("temp_min/Max x/y 陣列座標")
  
  arr_255point=gogogo(matrix,start_end,count_255)
  arr_255point= arr_255point[::-1] #########將numpy做反轉(從下走到上)且變成(col,row)#######
  #print("\nafter_turn arr_255point=\n",arr_255point)
  bump_total_punish=check_bump(arr_255point,min_row,min_col,max_row,max_col)
  return bump_total_punish

In [ ]:
#############LOSS4##############線段轉角是否符合規範##############
import sys
import numpy as np
import math
###########計算兩向量的夾角度數###################
def angle(v1, v2):
    dx1 = v1[2] - v1[0]
    dy1 = v1[3] - v1[1]
    dx2 = v2[2] - v2[0]
    dy2 = v2[3] - v2[1]
    angle1 = math.atan2(dy1, dx1)
    angle1 = float(angle1 * 180/math.pi)
    angle2 = math.atan2(dy2, dx2)
    angle2 = float(angle2 * 180/math.pi)
    
    if angle1*angle2 >= 0:
        included_angle = abs(angle1-angle2)
    else:
        included_angle = abs(angle1) + abs(angle2)
        if included_angle > 180:
            included_angle = 360 - included_angle
    return 180-included_angle

#############取與下面角度差距最小的值##############
def min_angle(angle):
  three=abs(angle-135)
  four=abs(angle-180)

  return min(three,four)

def check_other_angle(save_255point,count_255):
    v1=np.zeros(4)########存一個向量########
    v2=np.zeros(4)########存另一個向量########
    index=0
    m=0
    punish_other_angle=0
    for i in range(count_255-2):
      v1[index]=save_255point[0][i]
      v1[index+1]=save_255point[1][i]
      v1[index+2]=save_255point[0][i+1]
      v1[index+3]=save_255point[1][i+1]
      v2[index]=save_255point[0][i+1]
      v2[index+1]=save_255point[1][i+1]
      v2[index+2]=save_255point[0][i+2]
      v2[index+3]=save_255point[1][i+2] 
      #print("v1=",v1)
      #print("v2=",v2)  
      ang=round(angle(v1,v2),0)
      print("ang=",ang)
      if ang==135 or ang==180:
        continue
      else:
        ang=min_angle(ang)
        punish_other_angle=punish_other_angle+ang
    if punish_other_angle==0:
      print("\nNo Punish... \npunish_other_angle=0")
    else:
      print("\nPunish... \npunish_other_angle=",punish_other_angle)
    return punish_other_angle
def LOSS4(matrix):
  print("#############LOSS4##############線段轉角是否符合規範##############")
  punish_other_angle=0
  count_255=find_255point(matrix)
  #print("count_255=",count_255)
  start_end=find_start_end(matrix)
  #print(start_end)
  arr_255point=gogogo(matrix,start_end,count_255)
  punish_other_angle=check_other_angle(arr_255point,count_255)
  return punish_other_angle


In [ ]:
#############LOSS7##############最短路徑##############
def Distance(p1):
  #print("p2[0]=",p2[0])
  #print("p2[1]=",p2[1])
  dx = abs(p1[0] - p1[2])
  dy = abs(p1[1] - p1[3])
  num=dx*dx+dy*dy
  d = num**0.5
  return d

####目標的位置
#goal_row=45
#goal_col=60
def LOSS7(matrix):
  print("#############LOSS7##############最短路徑##############")
  shortest_distance=0
  count_255=find_255point(matrix)
  start_end=find_start_end(matrix)
  #p2=[0]*4
  p3=[0]*4
  #p2[0]=start_end[0][0]
  #p2[1]=start_end[0][1]
  p3[0]=start_end[0][0]
  p3[1]=start_end[0][1]
  #p2[2]=start_end[1][0]
  #p2[3]=start_end[1][1]
  p3[2]=goal_row
  p3[3]=goal_col
  last_node_to_goal=((start_end[1][0]-goal_row)**2+(start_end[1][1]-goal_col)**2)**0.5
  shortest_distance=Distance(p3)
  arr_255point=gogogo(matrix,start_end,count_255)
  #print("\n實際走線距離:")
  p1=[0]*4
  total_dis=0
  for i in range(len(arr_255point[0])):
    if i==len(arr_255point[0])-1:
      break
    p1[0]=arr_255point[0][i]
    p1[1]=arr_255point[1][i]
    p1[2]=arr_255point[0][i+1]
    p1[3]=arr_255point[1][i+1]
    total_dis=total_dis+Distance(p1)
  total_dis=total_dis+last_node_to_goal
  print("shortest_dis=",abs(shortest_distance))
  print("actual_dis=",abs(total_dis))
  print("total dis punish=",abs((total_dis-shortest_distance)/shortest_distance))
  return (total_dis-shortest_distance)/shortest_distance





In [ ]:
#############很重要不能刪!!!!(有這個才能將tf轉成numpy)########################
tf.config.run_functions_eagerly(True)
def our_loss(generated_images):
  #print(type(generated_images))
  generated_images_numpy=generated_images.numpy()
  #print(type(generated_images_numpy)) 
  matrix = np.zeros((64,64), dtype = float)
  matrix=custom_model(generated_images_numpy)
  matrix=turn_result(matrix)
  max_punish=45+10+45*10+LOSS7(matrix)   
  total_punish=LOSS1(matrix)+LOSS2(matrix)+LOSS4(matrix)+LOSS7(matrix)
  print("#########################total punish#####################")
  print("total punish=",abs(total_punish))
  print("max punish=",abs(max_punish))
  gen_total_loss=total_punish/max_punish
  print("gen_total_loss=",abs(gen_total_loss))
  punish = tf.convert_to_tensor(gen_total_loss, dtype=tf.float32)
  return punish

In [ ]:
####################custom loss function#################################
def custom_loss_function(flag,generated_images,y_true, y_pred):
  #print(generated_images.shape)
  if flag==1:
    return custom_predict_loss(y_true, y_pred)
  else:
    gen_loss=our_loss(generated_images)
    value = generator_loss(y_true, y_pred)
    return value+gen_loss

In [ ]:
class GAN(keras.Model):
    def __init__(self, custom_predict, generator, latent_dim):
        super(GAN, self).__init__()
        self.custom_predict = custom_predict
        self.generator = generator
        self.latent_dim = latent_dim

    #def compile(self, d_optimizer, g_optimizer):
    def compile(self, d_optimizer, g_optimizer, loss_fn):
        super(GAN, self).compile()
        self.d_optimizer = d_optimizer
        self.g_optimizer = g_optimizer
        self.loss_fn = loss_fn
        self.d_loss_metric = keras.metrics.Mean(name="d_loss")
        self.g_loss_metric = keras.metrics.Mean(name="g_loss")

    @property
    def metrics(self):
        return [self.d_loss_metric, self.g_loss_metric]

    def train_step(self, real_images):
        # Sample random points in the latent space
        batch_size = tf.shape(real_images)[0]
        random_latent_vectors = tf.random.normal(shape=(batch_size, self.latent_dim))

        # Decode them to fake images
        generated_images = self.generator(random_latent_vectors)

        # Combine them with real images
        combined_images = tf.concat([generated_images, real_images], axis=0)
        
        # Assemble labels discriminating real from fake images
        labels = tf.concat(
            [tf.ones((batch_size, 1)), tf.zeros((batch_size, 1))], axis=0
        )
        # Add random noise to the labels - important trick!
        #labels += 0.05 * tf.random.uniform(tf.shape(labels))

        
        with tf.GradientTape() as tape:
            #print("combined_images=",combined_images)
            predictions = custom_predictor(combined_images)
            predictions = self.custom_predict(combined_images)
            predictions = tf.convert_to_tensor(predictions, dtype=tf.float32)
            #predictions = self.custom_predict(combined_images)
            #print("prediction=",predictions)
            #print("type(prediction)=",type(predictions))
            flag=1
            d_loss = self.loss_fn(flag,generated_images,labels, predictions)
            #print("d_loss=",d_loss)
        #print("self.custom_predict.trainable_weights=",self.discriminator.trainable_weights)
        grads = tape.gradient(d_loss, self.custom_predict.trainable_weights)
        #print("grads=",grads)
        self.d_optimizer.apply_gradients(
            zip(grads, self.custom_predict.trainable_weights)
        )

        # Sample random points in the latent space
        random_latent_vectors = tf.random.normal(shape=(batch_size, self.latent_dim))

        # Assemble labels that say "all real images"
        misleading_labels = tf.zeros((batch_size, 1))

        
        with tf.GradientTape() as tape:
            predictions = self.custom_predict(self.generator(random_latent_vectors))
            #g_loss = self.loss_fn(misleading_labels, predictions)
            flag=0
            g_loss = self.loss_fn(flag,generated_images,misleading_labels, predictions)
        grads = tape.gradient(g_loss, self.generator.trainable_weights)
        self.g_optimizer.apply_gradients(zip(grads, self.generator.trainable_weights))

        # Update metrics
        self.d_loss_metric.update_state(d_loss)
        self.g_loss_metric.update_state(g_loss)
        return {
            
            "g_loss": self.g_loss_metric.result(),
        }


In [ ]:
##########用來將最後一個轉折點與終點相連##############
import numpy as np

def case1(arr_255point,matrix,count_255):
  arr_255point[0][count_255-1]=start_end[1][0]
  arr_255point[1][count_255-1]=start_end[1][1]
  #print("arr_255point=",arr_255point)
  new_node=np.zeros(2,dtype=np.int)
  diff_row=0
  diff_col=0
  last_turn_row=int(arr_255point[0][len(arr_255point[0])-2])
  last_turn_col=int(arr_255point[1][len(arr_255point[0])-2])
  diff_row=int(goal_row-arr_255point[0][count_255-2])
  diff_col=int(goal_col-arr_255point[1][count_255-2])
  if diff_col==0:######正下方#####
    for i in range(1,diff_row):
      matrix[last_turn_row+i][last_turn_col]=70
    return matrix
  if diff_row<diff_col:
    new_node[0]=goal_row
    new_node[1]=arr_255point[1][count_255-2]+diff_row
  if diff_col<diff_row:
    new_node[1]=goal_col
    new_node[0]=arr_255point[0][count_255-2]+diff_col
  if diff_col==diff_row:
    row=int(arr_255point[0][count_255-2])
    col=int(arr_255point[1][count_255-2])
    for i in range(1,diff_col):
      matrix[row+i][col+i]=80
    return matrix
  print("new_node=",new_node)

  draw_line=np.zeros((3,2),dtype=np.int)

  ##########最後一個轉折點##############
  draw_line[0][0]=arr_255point[0][count_255-2]
  draw_line[0][1]=arr_255point[1][count_255-2]
  ##########新的轉折點##############
  draw_line[1][0]=new_node[0]
  draw_line[1][1]=new_node[1]
  ##########goal_node##############
  draw_line[2][0]=goal_row
  draw_line[2][1]=goal_col
  #######draw_line############
  now_row=draw_line[0][0]
  now_col=draw_line[0][1]
  if now_row!=goal_row or now_col!=goal_col:
    go_dis=draw_line[1][0]-draw_line[0][0]
    #print("go_dis=",go_dis)
    for i in range(1,go_dis):
      matrix[now_row+i][now_col+i]=80
  now_row=draw_line[1][0]
  now_col=draw_line[1][1]
  matrix[now_row][now_col]=255
  if now_row==goal_row:
    go_col=goal_col-draw_line[1][1]
    for i in range(1,go_col):
      matrix[now_row][now_col+i]=10
  if now_col==goal_col:
    go_row=goal_row-draw_line[1][0]
    for i in range(1,go_row):
      matrix[now_row+i][now_col]=70
  return matrix
def case3(arr_255point,matrix,count_255):
  new_node=np.zeros((2,2),dtype=np.int)
  diff_row=0
  diff_col=0
  last_turn_row=arr_255point[0][len(arr_255point[0])-2]
  last_turn_col=arr_255point[1][len(arr_255point[0])-2]
  diff_row=int(last_turn_row-goal_row)
  diff_col=int(goal_col-last_turn_col)
  print("diff_row=",diff_row)
  print("diff_col=",diff_col)
  if diff_row==diff_col:
    for i in range(1,diff_row+1):
      matrix[int(last_turn_row)-i][int(last_turn_col)+i]=20
  elif diff_row>diff_col:
    matrix[int(last_turn_row-diff_col)][goal_col]=255
    for i in range(1,diff_col):
      matrix[int(last_turn_row)-i][int(last_turn_col)+i]=20
    diff_row2=int(last_turn_row-diff_col-goal_row)
    for i in range(1,diff_row2):
      matrix[int(last_turn_row-diff_col)-i][goal_col]=30

  return matrix
def case2(arr_255point,matrix,count_255):
  new_node=np.zeros((2,2),dtype=np.int)
  diff_row=0
  diff_col=0
  last_turn_row=arr_255point[0][len(arr_255point[0])-2]
  last_turn_col=arr_255point[1][len(arr_255point[0])-2]
  diff_row=int(last_turn_row-goal_row)
  diff_col=int(goal_col-last_turn_col)
  print("diff_row=",diff_row)
  print("diff_col=",diff_col)
  if diff_row==0:
    for i in range(1,diff_col):
      matrix[int(last_turn_row)][int(last_turn_col+i)]=10
  if diff_row!=0 and diff_row<diff_col:
    new_node[1][0]=goal_row+2*diff_row
    new_node[1][1]=goal_col-2*diff_row
    print(new_node[1])
    new_node[0][0]=new_node[1][0]
    new_node[0][1]=last_turn_col+(new_node[0][0]-last_turn_row)
    matrix[new_node[0][0]][new_node[0][1]]=255
    matrix[new_node[1][0]][new_node[1][1]]=255
    print(new_node[0])
    ############畫線##############
    ##########斜線下#################
    go_dis=int(new_node[0][0]-last_turn_row)
    for i in range(1,go_dis):
      matrix[int(last_turn_row)+i][int(last_turn_col)+i]=80
    ########水平線##############
    go_col=int(new_node[1][1]-new_node[0][1])
    for i in range(1,go_col):
      matrix[new_node[0][0]][new_node[0][1]+i]=10
    ##########斜線上#################
    go_dis=int(goal_col-new_node[1][1])
    for i in range(1,go_dis):
      matrix[new_node[1][0]-i][new_node[1][1]+i]=20
  else:
    print("case3")
    matrix=case3(arr_255point,matrix,count_255)#############硬化出一條線###########
  return matrix
def case4(arr_255point,matrix,count_255):
  new_node=np.zeros((2,2),dtype=np.int)
  diff_row=0
  diff_col=0
  last_turn_row=int(arr_255point[0][len(arr_255point[0])-2])
  last_turn_col=int(arr_255point[1][len(arr_255point[0])-2])
  diff_row=int(goal_row-last_turn_row)
  diff_col=int(last_turn_col-goal_col)
  print("diff_row=",diff_row)
  print("diff_col=",diff_col)
  if diff_row==0:#########正左############
    for i in range(1,diff_col):
      matrix[goal_row][last_turn_col-i]=50
    return matrix
  if diff_row==diff_col:#####正左下#######
    for i in range(1,diff_row+1):
      matrix[last_turn_row+i][last_turn_col-i]=60
  if diff_row<diff_col:#####左下#######
    matrix[goal_row][last_turn_col-diff_row]=255
    for i in range(1,diff_row):
      matrix[last_turn_row+i][last_turn_col-i]=60
    go_col=(last_turn_col-diff_row)-goal_col
    for i in range(1,go_col):
      matrix[goal_row][(last_turn_col-diff_row)-i]=50
  if diff_col<diff_row:#####左下#######
    go_row=diff_row-diff_col
    matrix[last_turn_row+go_row][last_turn_col]=255
    for i in range(1,go_row):
      matrix[last_turn_row+i][last_turn_col]=70
    for i in range(1,diff_col):
      matrix[(last_turn_row+go_row)+i][last_turn_col-i]=60 
  return matrix
def case5(arr_255point,matrix,count_255):
  new_node=np.zeros((2,2),dtype=np.int)
  diff_row=0
  diff_col=0
  last_turn_row=int(arr_255point[0][len(arr_255point[0])-2])
  last_turn_col=int(arr_255point[1][len(arr_255point[0])-2])
  diff_row=int(last_turn_row-goal_row)
  diff_col=int(last_turn_col-goal_col)
  print("diff_row=",diff_row)
  print("diff_col=",diff_col)
  if diff_row>diff_col:
    #print("AAAAAAAAAAAAAAA")
    matrix[last_turn_row-diff_col][goal_col]=255
    for i in range(1,diff_col):
      matrix[last_turn_row-i][last_turn_col-i]=40
    go_row=diff_row-diff_col
    #print("go_row=",go_row)
    for i in range(1,go_row):
      matrix[(last_turn_row-diff_col)-i][goal_col]=30
  if diff_row<diff_col:
    go_col=diff_col-diff_row
    #print("go_col=",go_col)
    #print("last_turn_row=",last_turn_row)
    #print("last_turn_col-go_col=",last_turn_col-go_col)
    matrix[last_turn_row][last_turn_col-go_col]=255
    for i in range(1,go_col):
      matrix[last_turn_row][last_turn_col-i]=50
    go_dis=diff_col-go_col
    #print("go_row=",go_row)
    for i in range(1,go_dis):
      matrix[last_turn_row-i][last_turn_col-go_col-i]=40
  
  return matrix
def gogogo(matrix,start_end,count_255):
    index_x=int(start_end[0][0])####初始位置
    index_y=int(start_end[0][1])
    end_x=start_end[1][0]
    end_y=start_end[1][1]
    
    
    arr_255point=np.zeros((2,count_255))
    arr_255point[0][0]=start_end[0][0]
    arr_255point[1][0]=start_end[0][1]
    before=-1
    run=0
    flag=0
    while(run<(count_255-1)):
      flag=0
      run=run+1
      #print("index_x=",index_x)
      #print("index_y=",index_y)
      if index_y+1<64:
        if matrix[index_x][index_y+1]!=float(0) and flag==0:
          for i in range(64):
            index_y=index_y+1
            if index_y+1<64:
              if matrix[index_x][index_y]==float(255) and flag==0:
                break
            else:
              break
            
          arr_255point[0][run]=index_x
          arr_255point[1][run]=index_y
          flag=1
          #print("arr_255point=aaaa",arr_255point)
      if index_y+1<64 and index_x+1<64:
        if matrix[index_x+1][index_y+1]!=float(0) and flag==0:
          for i in range(64):
            index_y=index_y+1
            index_x=index_x+1
            if index_y<64 and index_x<64:
              if matrix[index_x][index_y]==float(255):
                break
          #print("index_x=",index_x)
          arr_255point[0][run]=index_x
          arr_255point[1][run]=index_y
          flag=1
          #print("arr_255point=bbbb",arr_255point)
      if index_x+1<64:
        if matrix[index_x+1][index_y]!=float(0) and flag==0:
          for i in range(64):
            index_x=index_x+1
            #print(index_x,"cccc",index_y)
            if index_x<64:
              if matrix[index_x][index_y]==float(255):
                break
          arr_255point[0][run]=index_x
          arr_255point[1][run]=index_y
          flag=1
          
      if index_y-1>=0:
        if matrix[index_x][index_y-1]!=float(0) and flag==0:
          for i in range(64):
            index_y=index_y-1
            #print(index_x,"dddd",index_y)
            if matrix[index_x][index_y]==float(255):
              break
          arr_255point[0][run]=index_x
          arr_255point[1][run]=index_y
          flag=1
          #print("arr_255point=dddd",arr_255point)
      if index_x+1<64 and index_y-1>=0:
        if matrix[index_x+1][index_y-1]!=float(0) and flag==0: 
          for i in range(64):
            index_x=index_x+1
            index_y=index_y-1
            #print(index_x,"eeee",index_y)
            if matrix[index_x][index_y]==float(255):
              break
          arr_255point[0][run]=index_x
          arr_255point[1][run]=index_y
          flag=1
          #print("arr_255point=eeee",arr_255point)
      #print("走線順序:")
      #for i in range(len(arr_255point[0])):
      #print("(",arr_255point[0][i],",",arr_255point[1][i],")")
    #print("\nbefore turn arr_255point=\n",arr_255point)
    return arr_255point

def draw_bump(matrix):
  ##############假設bump座標########
  min_row_temp=26
  min_col_temp=18
  max_row_temp=35
  max_col_temp=35
  for i in range(len(matrix)):
    for j in range(len(matrix[0])):
      if matrix[i][j]==0:
        if i>=min_row_temp and i<=max_row_temp and j>=min_col_temp and j<=max_col_temp:
          #print("i=",i)
          #print("j=",j)
          matrix[i][j]=9
  return matrix

start_end=np.zeros((2, 2),dtype=np.int)
start_end[0][0]=start_row
start_end[0][1]=start_col
start_end[1][0]=goal_row
start_end[1][1]=goal_col
print("start_row=",start_row)
print("start_col=",start_col)
print("goal_row=",goal_row)
print("goal_col=",goal_col)
def draw_result(matrix,epoch):
  count_255=0
  for i in range(64):
    for j in range(64):
      if matrix[i][j]==255:
        count_255=count_255+1
  print("count_255=",count_255)
  print(matrix)
  
  
  

  arr_255point=gogogo(matrix,start_end,count_255)
  print("arr_255point=",arr_255point)

  flag=1
  if flag==0:
    matrix[goal_row][goal_col]=255
  if flag==1:
    if arr_255point[0][len(arr_255point[0])-2]<goal_row and arr_255point[1][len(arr_255point[0])-2]<=goal_col:
      print("case1")#######終點在最後一個轉折點的右下方或正下方############
      matrix=case1(arr_255point,matrix,count_255)
    if arr_255point[0][len(arr_255point[0])-2]>=goal_row and arr_255point[1][len(arr_255point[0])-2]<goal_col:
      print("case2")#######終點在最後一個轉折點的右上方 和 正右方############
      matrix=case2(arr_255point,matrix,count_255)
    if arr_255point[0][len(arr_255point[0])-2]<=goal_row and arr_255point[1][len(arr_255point[0])-2]>goal_col:
      print("case4")#######終點在最後一個轉折點的左下方 和 正左方############
      matrix=case4(arr_255point,matrix,count_255)
    if arr_255point[0][len(arr_255point[0])-2]>goal_row and arr_255point[1][len(arr_255point[0])-2]>goal_col:
      print("case5")#######終點在最後一個轉折點的左上方############
      matrix=case5(arr_255point,matrix,count_255)

  #matrix=draw_bump(matrix)
  #########寫檔##############
  path = './final_result9_'+str(epoch)+'.txt'
  f_result = open(path, 'w')
  for i in range(64):
    for j in range(64):
      f_result.write(str(matrix[i][j])+" ")  
    f_result.write("\n")  
  f_result.close()

start_row= 2
start_col= 23
goal_row= 23
goal_col= 28


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:290: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


In [ ]:
class GANMonitor(keras.callbacks.Callback):
    def __init__(self, num_img=3, latent_dim=128):
        self.num_img = num_img
        self.latent_dim = latent_dim

    def on_epoch_end(self, epoch, logs=None):
        random_latent_vectors = tf.random.normal(shape=(self.num_img, self.latent_dim))
        generated_images = self.model.generator(random_latent_vectors)
        generated_images = (generated_images+1)*255/2####原本/255
        generated_images.numpy()
        generated_image_np=generated_images.numpy()
        matrix = np.zeros((64,64), dtype = float)
        matrix=custom_model(generated_image_np)
        matrix=turn_result(matrix)
        
        if epoch%2==0:
          draw_result(matrix,epoch)########畫最後一個轉折點到終點的連線#########
          path = 'generated_img_arr'+str(epoch)+'.txt'
          f_result = open(path, 'w')
          for i in range(64):
            for j in range(64):
              f_result.write(str(matrix[i][j])+" ")  
            f_result.write("\n")  
          f_result.close()
          
        

In [ ]:
epochs =  501  # In practice, use ~100 epochs

gan = GAN(custom_predict=custom_predict, generator=generator, latent_dim=latent_dim)
gan.compile(
    d_optimizer=keras.optimizers.Adam(learning_rate=0.0001, decay=1e-9),
    g_optimizer=keras.optimizers.Adam(learning_rate=0.0001, decay=1e-9),
    #loss_fn=keras.losses.BinaryCrossentropy(),
    loss_fn=custom_loss_function,
    
)

gan.fit(
    dataset_6464, epochs=epochs, callbacks=[GANMonitor(num_img=10, latent_dim=latent_dim)]
)

Epoch 1/501
--------------------------------------------

num(turn_node)= 2
turn_result=
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
#############LOSS7##############最短路徑##############
shortest_dis= 21.587033144922902
actual_dis= 8.485281374238571
total dis punish= 0.6069269307517489
###################LOSS1###########################產生的起點終點是否符合要求################
start_end= [[ 2 23]
 [23 28]]
last_node= [23 28]
last_angle= 0.0
##############LOSS2##############################check bump############

bump_punish_time= 0
#############LOSS4##############線段轉角是否符合規範##############
ang= 180.0
ang= 180.0

No Punish... 
punish_other_angle=0
#############LOSS7##############最短路徑##############
shortest_dis= 21.587033144922902
actual_dis= 8.485281374238571
total dis punish= 0.6069269307517489
#########################total punish#####################
total punish= 0.6069269307517489
max pu

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


 1/21 [>.............................] - ETA: 3:12 - g_loss: 0.6861--------------------------------------------

num(turn_node)= 2
turn_result=
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
#############LOSS7##############最短路徑##############
shortest_dis= 21.587033144922902
actual_dis= 10.48528137423857
total dis punish= 0.5142787198293332
###################LOSS1###########################產生的起點終點是否符合要求################
start_end= [[ 2 23]
 [23 28]]
last_node= [23 28]
last_angle= 0.0
##############LOSS2##############################check bump############

bump_punish_time= 0
#############LOSS4##############線段轉角是否符合規範##############
ang= 135.0
ang= 135.0
ang= 180.0

No Punish... 
punish_other_angle=0
#############LOSS7##############最短路徑##############
shortest_dis= 21.587033144922902
actual_dis= 10.48528137423857
total dis punish= 0.5142787198293332
#########################total p

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:125: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


Epoch 2/501
--------------------------------------------

num(turn_node)= 2
turn_result=
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
#############LOSS7##############最短路徑##############
shortest_dis= 21.587033144922902
actual_dis= 6.0
total dis punish= 0.7220553672327523
###################LOSS1###########################產生的起點終點是否符合要求################
start_end= [[ 2 23]
 [23 28]]
last_node= [23 28]
last_angle= 0.0
##############LOSS2##############################check bump############

bump_punish_time= 0
#############LOSS4##############線段轉角是否符合規範##############
ang= 180.0
ang= 180.0

No Punish... 
punish_other_angle=0
#############LOSS7##############最短路徑##############
shortest_dis= 21.587033144922902
actual_dis= 6.0
total dis punish= 0.7220553672327523
#########################total punish#####################
total punish= 0.7220553672327523
max punish= 504.27794463276723
gen

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


串流輸出內容已截斷至最後 5000 行。
start_end= [[ 2 23]
 [23 28]]
last_node= [23 28]
last_angle= 0.0
##############LOSS2##############################check bump############

bump_punish_time= 0
#############LOSS4##############線段轉角是否符合規範##############
ang= 135.0
ang= 135.0

No Punish... 
punish_other_angle=0
#############LOSS7##############最短路徑##############
shortest_dis= 21.587033144922902
actual_dis= 6.82842712474619
total dis punish= 0.6836792217390846
#########################total punish#####################
total punish= 0.6836792217390846
max punish= 504.3163207782609
gen_total_loss= 0.001355655554997766
14/21 [===================>..........] - ETA: 2s - g_loss: 1.1782--------------------------------------------

num(turn_node)= 2
turn_result=
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
#############LOSS7##############最短路徑##############
shortest_dis= 21.587033144922902
actual_dis= 9.

KeyboardInterrupt: ignored